export const rows = [
    {
        id: 1,
        user: "user1",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Approved",
    },
    {
        id: 2,
        user: "user2",
        type: "Non Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Pending",
    },
    {
        id: 3,
        user: "user1",
        type: "NonCasual",
        days: 4,
        startDate: "1 March 2022",
        endDate: "4 March 2022",
        status: "Pending",
    },
    {
        id: 4,
        user: "user10",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Rejected",
    },
    {
        id: 5,
        user: "user3",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Rejected",
    },
    {
        id: 6,
        user: "user23",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Approved",
    },
    {
        id: 7,
        user: "user10",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Approved",
    },
    {
        id: 8,
        user: "user8",
        type: "Non Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Approved",
    },
    {
        id: 9,
        user: "user4",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Approved",
    },
    {
        id: 10,
        user: "user17",
        type: "Casual",
        days: 3,
        startDate: "1 March 2022",
        endDate: "3 March 2022",
        status: "Pending",
    },
];